/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface Mod {
  name: string
  version: string
}
export interface Piece {
  data: SpellData
  x: number
  y: number
}
export interface SpellData {
  key: string
  params?: SpellParams
  constant?: string
  comment?: string
}
export function spellFromSnbt(snbt: string): Spell
export function decodeSpellFromBytes(bytes: Array<number>): Spell
export function encodeBytesToUrlSafe(bytes: Array<number>): string
export function decodeUrlSafeToBytes(urlSafe: string): Array<number>
export function encodeSpellToBytes(spell: Spell): Array<number>
export function decodeSpell(urlSafe: string): Spell
export function encodeSpell(spell: Spell): string
export function spellToSnbt(spell: Spell): string
export class Spell {
  mods: Array<Mod>
  pieces: Array<Piece>
  name: string
  constructor(mods: Array<Mod>, pieces: Array<Piece>, name: string)
}
